version: "3.9"

services:
  laravel:
    build:
      context: .
      dockerfile: ./docker/laravel/Dockerfile
    volumes:
      - ./src/:/app
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=${DB_HOST}
      - DB_PORT=3306
      - DB_DATABASE=${DB_NAME}
      - DB_USERNAME=${DB_USER}
      - DB_PASSWORD=${DB_PASS}

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - ${WEB_PORT:-80}:80
    depends_on:
      - laravel
    volumes:
      - ./src/:/app
